version: "3"
services:
  hmpps-health-and-medication-api:
    build:
      context: .
    networks:
      - hmpps
    container_name: hmpps-health-and-medication-api
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ping"]
    environment:
      - SERVER_PORT=8080
      - HMPPS_AUTH_URL=http://hmpps-auth:8080/auth
      - SPRING_PROFILES_ACTIVE=dev
      - DPR_USER=dpr_user
      - DPR_PASSWORD=dpr_password

  hmpps-auth:
    image: quay.io/hmpps/hmpps-auth:latest
    networks:
      - hmpps
    container_name: hmpps-auth
    ports:
      - "8090:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/auth/health"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev
      - APPLICATION_AUTHENTICATION_UI_ALLOWLIST=0.0.0.0/0

  health-and-medication-data-db:
    image: postgres
    networks:
      - hmpps
    container_name: health-and-medication-data-db
    restart: unless-stopped
    ports:
      - "9432:5432"
    environment:
      - POSTGRES_PASSWORD=health-and-medication-data
      - POSTGRES_USER=health-and-medication-data
      - POSTGRES_DB=health-and-medication-data
      - TZ="Europe/London"
networks:
  hmpps:
