server:
  shutdown: immediate

hmpps-auth:
  url: "http://localhost:8090/auth"

spring:
  devtools:
    add-properties: true

  datasource:
    url: jdbc:postgresql://localhost:9432/health-and-medication-data?sslmode=prefer

  jpa:
    show-sql: true

database:
  username: health-and-medication-data
  password: health-and-medication-data
