---
# Per environment values which override defaults in hmpps-health-and-medication-api/values.yaml

generic-service:
  ingress:
    host: health-and-medication-api.hmpps.service.justice.gov.uk

  env:
    API_HMPPS_AUTH_BASE_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    API_PRISONER_SEARCH_BASE_URL: "https://prisoner-search.prison.service.justice.gov.uk"
    API_PRISON_API_BASE_URL: "https://prison-api.prison.service.justice.gov.uk"

  postgresDatabaseRestore:
    enabled: true
    namespace_secrets:
      rds-postgresql-instance-output:
        DB_NAME: "database_name"
        DB_USER: "database_username"
        DB_PASS: "database_password"
        DB_HOST: "rds_instance_address"
      rds-postgresql-instance-output-preprod:
        DB_NAME_PREPROD: "database_name"
        DB_USER_PREPROD: "database_username"
        DB_PASS_PREPROD: "database_password"
        DB_HOST_PREPROD: "rds_instance_address"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps-prisoner-profile-prod
  rdsAlertsDatabases:
    cloud-platform-2a10e6f376f54011: "HMPPS Health and Medication DB (prod)"
