---
# Per environment values which override defaults in hmpps-health-and-medication-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: health-and-medication-api-dev.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: "applicationinsights.dev.json"
    API_HMPPS_AUTH_BASE_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    API_PRISONER_SEARCH_BASE_URL: "https://prisoner-search-dev.prison.service.justice.gov.uk"
    API_PRISON_API_BASE_URL: "https://prison-api-dev.prison.service.justice.gov.uk"

  scheduledDowntime:
    enabled: true
    startup: '30 6 * * 1-5' # Start at 6.30am UTC Monday-Friday
    shutdown: '30 21 * * 1-5' # Stop at 9.30pm UTC Monday-Friday

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps-prisoner-profile-non-prod
  businessHoursOnly: true
  rdsAlertsDatabases:
    cloud-platform-74e3c6cbeecd38ba: "HMPPS Health and Medication DB (dev)"
